//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.QualityTools.UnitTestFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.QualityTools.UnitTestFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The test results are inconclusive because it is not fully implemented:
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string AssertMessageTestResultsInconclusive {
            get {
                return ResourceManager.GetString("AssertMessageTestResultsInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The test method &apos;{0}&apos; on class &apos;{1}&apos; is an invalid scenario because it is missing a ScenarioDescriptionAttribute. ähnelt.
        /// </summary>
        internal static string ExceptionMessageMessingScenarioDescriptionAttribute {
            get {
                return ResourceManager.GetString("ExceptionMessageMessingScenarioDescriptionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The class &apos;{0}&apos; is an invalid specification because it is missing a SpecificationDescriptionAttribute. ähnelt.
        /// </summary>
        internal static string ExceptionMessageMissingSpecificationDescriptionAttribute {
            get {
                return ResourceManager.GetString("ExceptionMessageMissingSpecificationDescriptionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The state property &apos;{0}&apos; could not be assigned because it has already been assigned with a type that cannot be assigned to. You are trying to assign a value to a property that has previously been declared as a &apos;{1}&apos; instance. ähnelt.
        /// </summary>
        internal static string ExceptionMessageStatePropertyNotAssignable {
            get {
                return ResourceManager.GetString("ExceptionMessageStatePropertyNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more of the post conditions failed for this specification:
        ///
        ///{0} ähnelt.
        /// </summary>
        internal static string FailMessageGrammersNotPassed {
            get {
                return ResourceManager.GetString("FailMessageGrammersNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unhandled exception occured whilst processing the specification:
        ///
        ///{0}] ähnelt.
        /// </summary>
        internal static string FailMessageUnhandledWhilstProcessingGrammars {
            get {
                return ResourceManager.GetString("FailMessageUnhandledWhilstProcessingGrammars", resourceCulture);
            }
        }
    }
}
